name: 📦 Build Flatpak

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  flatpak:
    name: build-flatpak
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      # Don't fail the whole workflow if one architecture fails
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Docker is required by the docker/setup-qemu-action which enables emulation
      - name: Install deps
        run: |
          dnf -y install docker
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Build Flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle:  de.haigruppe.summarizer.flatpak
          manifest-path: de.haigruppe.summarizer.json
          cache-key: flatpak-builder-${{ github.sha }}
          arch: ${{ matrix.arch }}
          branch: stable
      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: bilelmoussaoui/flatpak-github-actions/flat-manager@v4
        with:
          repository: ""
          flat-manager-url: https://flatpak.hachiman.nils.moe
          token: ${{ secrets.FLATMAN_TOKEN }}

